#!/bin/bash

echo
echo "[syslog]"
echo "--------"
syslog_tmp_file=./debug/headlog.tmp
syslog_file=./debug/fslog.log
dot_file=./debug/filedesc.dot
dd if=50m.img of=$syslog_tmp_file bs=1 count=32 skip=`echo "obase=10;ibase=16;26F0200" | bc` 2> /dev/null
dd if=50m.img of=$syslog_file bs=1 count=`head -n 1 $syslog_tmp_file | sed 's/\ //g'` skip=`echo "obase=10;ibase=16;26F0200" | bc` 2> /dev/null
echo >> $syslog_file
#echo "time: "`cat $syslog_file | head -n 3 | tail -n 1`
cat $syslog_file | sed '1,3d' > $dot_file
cat $dot_file | ./splitgraphs
#gthumb . &
#echo

exit 0
